version: '3.8'

services:
  app:
    image: python:3.9
    container_name: my_python_app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: python3 -m http.server 8000
  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    ports:
      - "3306:3306"
